### PR TITLE
Https Server

### PR DESCRIPTION
**Pull request by Matheus-Rangel**
Hi quinton, i am adding https to server allowing us to use the smartphone again. To make life easier when installing I already added the certificate files on the code itself since there not much problem for the WS data to be exposed.

### CODE REVIEW

**Comment by quinton-ashley** [comment]
I'm going to trust that this works and merge! Thanks for your work on this, I will make a new release soon.

**Comment by Matheus-Rangel** [comment]
Well, it worked locally here lol. I am playing Breath of the Wild again to get ready for Tears of the Kingdom and was having a hard time with my xbox controller using the analogies. Your solution is quite simple and really well implemented, and makes no sense to me that https is required to be able to get gyro information from the phone(why they did that?).

**Comment by Matheus-Rangel** [comment]
closes #15 #14 #13 #12 tested and working without any issues on cemu_1.25.4

**Comment by bigdefect** [comment]
Thanks @Matheus-Rangel! The timing is great, I was just looking at this repo the other day. Working for me on CEMU 2.0-39 on Windows 11 via an Android phone.

**Comment by PoPoChain** [comment]
@bigdefect can you tell me your settings? about input settings , thanks

**Comment by bigdefect** [comment]
> @bigdefect can you tell me your settings? about input settings , thanks

@popo89304 Not much to it. With cemu-no-gyro running, I added a controller in Cemu input settings, selected DSUController API, let it scan a couple of seconds until it found "Controller 1". Then opened its settings and checked "Use motion".

**Comment by PoPoChain** [comment]
@bigdefect After I sent you the message, my phone and XBOX controller are successfully running on CEMU 2.0  :))
My method is to select SDLController first, so that the system obtains the preset button, and then click the "+" next to it to keep the IP value under it unchanged.
The next method is the same as yours, so that you can use the XBOX controller at the same time, and you can also use cemu-no-gyro.
Thank you!

**Pull request merged**
